apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-api-load
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-api-load
  template:
    metadata:
      labels:
        app: nodejs-api-load
    spec:
      containers:
      - name: nodejs-api-load
        image: itaybeyder/nodejs-api-load:2
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-api-load
  namespace: test
spec:
  selector:
    app: nodejs-api-load
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP